# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  tags:
    include:
      - 1.*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: ARTIFACT_VERSION
    value: 0.0.0

steps:
  - bash:
       echo "y" | sudo $(ANDROID_SDK_ROOT)/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    displayName: 'Setup NDK 21.0.6113669'

  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
      artifactsFeeds: 'middleware, nextgen'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
    displayName: gradlew build

  - task: CopyFiles@2
    displayName: 'Copy .aar files to artifact staging directory'
    inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.aar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()