# Android
# assembleRelease your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save assembleRelease artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  tags:
    include:
      - 1.*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: ARTIFACT_VERSION
    value: 0.0.0

steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=ARTIFACT_VERSION]$(git describe --tags)"
    displayName: 'Setup ARTIFACT_VERSION from tag'

  - bash:
       echo "y" | sudo $(ANDROID_SDK_ROOT)/tools/bin/sdkmanager --install "ndk;21.1.6352462" --sdk_root=${ANDROID_SDK_ROOT}
    displayName: 'Setup NDK 21.1.6352462'

  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
      artifactsFeeds: 'middleware, nextgen'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :nextgen-core:assembleRelease :nextgen-middleware:assembleRelease :nextgen-mmt:assembleRelease :nextgen-view:assembleRelease'
    displayName: gradlew clean and build

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':nextgen-middleware:testReleaseUnitTest'
    displayName: gradlew test

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':nextgen-core:publish :nextgen-middleware:publish :nextgen-mmt:publish :nextgen-view:publish -PartifactVersion=$(ARTIFACT_VERSION)'
    displayName: gradlew publish

  - task: CopyFiles@2
    displayName: 'Copy .aar files to artifact staging directory'
    inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.aar'
        TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
